### ISSUE TITLE
how to rerender?

### ISSUE THREAD

**Issue by varzhonglei** [trickeyd/react-native-modal#1]
`outSide`
  useModal(
    () => <MyModal onClose={() => setModalIsVisible(false)} />,
    modalIsVisible
    options
  )
  
  when the `outSide`  render, `MyModal`  don't get render.

**Comment by trickeyd** [comment]
Hello!
Thanks for raising the issue!!
I had made some "optimisations" recently and I hadn't noticed that they had messed up the render pipeline.

In 1.2.2 have added a dependencies array, so you can decide when to rerender. Often this will be the same as the properties your modal accepts.

I have tidied up the arguments a bit and added the renderModal to the config object, so the above would now look like this:

```
useModal(
  {
    renderModal: () => <MyModal onClose={() => setModalIsVisible(false)}  someProp={someProp}/>,
  },
  modalIsVisible,
  [someProp] // this changing will trigger the render
)
```

Thanks for checking it out - let me know how you get on.

**Comment by trickeyd** [comment]
Hello @varzhonglei! Just wondering if this helped at all? 🙂

**Comment by varzhonglei** [comment]
Hi, @trickeyd! Thanks you do.
I think it worked, I would to try it next time.
